{% set version = "1.9.8" %}

package:
  name: jack
  version: {{ version }}

source:
  url: http://jackaudio.org/downloads/jack-audio-connection-kit-{{ version }}.tar.gz
  sha256: 5a1d64118034d58529d68a9af42710f9d4843536257c496118065ea3d3e4ae2c

build:
  number: 0
  skip: True  # [win or osx]
  run_exports:
    - {{ pin_subpackage('jack', max_pin='x.x') }}

requirements:
  build:
    - libdb
  run:
    - libdb

test:
  commands:
    - conda inspect linkages -p $PREFIX jack  # [not win]
    - conda inspect objects -p $PREFIX jack  # [osx]

about:
  home: http://jackaudio.org/
  license: LGLP-2.0
  license_file: COPYING.LGPL
  summary: 'Audio connection kit.'

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
