travis:
  secure:
    BINSTAR_TOKEN: fF+i/XlO7PAQf1vkt90kXiaNSrFx3nb3bpL8GGDgMozQPjQA9FyiLhKvFWSYO3TNGevPzQWm89QZjcfJ2hAoU/VAArlFXQ6aKz/Kz7vH5mdpP2SWV48nOQd73KctXKpWsBdYX1rCm348fgi1a9j+6vvXa0Dn3YXHd10yXIpTXVkDe/9xEwZ+Wv00bfmKL6j7n1TmARzSsg3A0/fPyFXJCnHi2mC50OQuuQva7oBT0ziB9E0/EeGpe1jQS5YAFpB1Qrig7QHF7tyNO5k0nqf3Auq0sSAleb2dkiKPIDqjkikTUPiuB5Rf1RUR1eMY+NJT67daluJHNyB2ddxDSTxGJUxgcqslAsgkN8+Dq8NYQCEDA6302LSnH+4oYiFjACkuRp4Cwz4h6bJyDWVLFxlTnS2ury7hOC4NpIo2vzsrZ4FWhd/O0qpma8Np6Ku3EI9sRQJKz3HOZlHVk///OS4/iR7G4EAMsp5HFf2UW2g7k4rIX85KVUDD23iQxTHY7eRE/KMpDQ+E4GONNM/cVYi+6lzjkt692oQD9ZHcusuw8SyZXLVnsOs2pUcGuMpAU8HagJoZsIhQu+TaLoqVVpcxRzeFrW9ruGoEbpEJVckAvNgUtHvDlVmc6mzE7jtouTXTEWgg/uP/rrC9ICHxKApthdFQy1lYkAOyCOp5TXxFlEA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
